### ISSUE TITLE
Control Plane Load-Balancing issue with IPVS

### ISSUE THREAD

**Issue by Cloud-Mak** [kube-vip/kube-vip#895]
**Describe the bug**
After setting up HA k8s with 3 nodes when tried enabling [LB for control planes](https://kube-vip.io/docs/about/architecture/#control-plane-load-balancing), the ipvsadm is showing odd beheviour. it was only showing 1st master node m1 (which was initiated 1st in k8s) avialable as backend for IPVS LB. Even though lb_enable was set for rest of nodes (m2 & m3) kube-vip.yaml

m1 ipvsadm -ln 

```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.30.84.160:6443 rr
  -> 172.30.84.154:6443           Local   1      0          0

```

After rebooting m1 (.154), the VIP shifted to m3 (new leader) and ipvs command on m3 shown only two nodes available as m2 (.155) & m3 (.156) backend for IPVS.  m1 is not getting added to backend for IPVS even after it comes back online.

Here are kube-VIP logs for m3 while m1 is rebooting.

```
time="2024-07-12T16:27:55Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2024-07-12T16:27:55Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2024-07-12T16:27:55Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [172.30.84.160/ens160]"
time="2024-07-12T16:27:55Z" level=error msg="Error querying backends file does not exist"
time="2024-07-12T16:27:55Z" level=info msg="Created Load-Balancer services on [172.30.84.160:6443]"
time="2024-07-12T16:27:55Z" level=info msg="Added backend for [172.30.84.160:6443] on [172.30.84.155:6443]"
time="2024-07-12T16:27:55Z" level=info msg="failed check k8s server version: Get \"https://172.30.84.154:6443/version?timeout=10s\": dial tcp 172.30.84.154:6443: connect: connection refused"
time="2024-07-12T16:27:55Z" level=info msg="Added backend for [172.30.84.160:6443] on [172.30.84.156:6443]"
```

Eventually I had to stop kube-vip container on m3 (via crictl stop ID), it created a new kube-vip container immediately and then m1 appeard as background of IPVS.

```
time="2024-07-12T16:46:00Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [172.30.84.160/ens160]"
I0712 16:46:00.656739       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-svcs-lock
time="2024-07-12T16:46:00Z" level=info msg="(svcs) starting services watcher for all namespaces"
time="2024-07-12T16:46:00Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2024-07-12T16:46:00Z" level=info msg="Added backend for [172.30.84.160:6443] on [172.30.84.155:6443]"
```

ipvs on m3 now 

```
root@m3:~$ ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.30.84.160:6443 rr
  -> 172.30.84.154:6443           Local   1      3          0
  -> 172.30.84.155:6443           Local   1      2          1
  -> 172.30.84.156:6443           Local   1      1          0
```

Now if you reboot m3, the new elected leader will show only two backend for IPVS even after m3 comes online. Unless you stop kube-vip on leader. 

**To Reproduce**
https://kube-vip.io/docs/about/architecture/#control-plane-load-balancing
setup Control Plane Load-Balancing by using this steps.

**Expected behavior**
Even if node reboots, it should become part of IPVS LB once it comes online without killing kube-VIP container on leader. Observed this behaviour multiple times.

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 22]
 - Kubernetes Version: [v.1.30.2]
 - Kube-vip Version: [0.8.1]

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: ens160
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 172.30.84.160
    - name: prometheus_server
      value: :2112
    - name: lb_enable
      value: "true"
    image: ghcr.io/kube-vip/kube-vip:v0.8.1
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
```

**Additional context**

**Comment by aviral-agarwal** [comment]
Facing exactly the same issue. 3 control plane nodes vm1, vm2, vm3
After kubernetes setup, only the initial leader (vm1) in ipvs for load balancing
if I shut down vm1, the next leader (say vm2) has both available vm2, vm3

but if vm1 is back up, the ipvs is not updated to have vm1

you were able to figure out a fix for this @Cloud-Mak ?

Any help is appreciated

this is inconsistent behaviour
and may be because the kube-vip pod (using static pod) is not able to reach to the control plane nodes. 
But pod logs are telling me it is not even trying i.e. no retries or failure after initial initialization

hence maybe stopping kube-vip pod helps

**Comment by Cloud-Mak** [comment]
Hi,

Nope. I couldn't find any fix. This is something devs of kube-vip needs to
test & fix. I wonder how did this is still an issue. It's a critical
function.
--
makrand
sent from handheld using (over)smart autocorrect.... excuse typos.

**Comment by aviral-agarwal** [comment]
Yes, it is critical and an issue. 
As suggested by you @Cloud-Mak
Stopping the kube-vip container on the leader forces it to refresh, and then it can detect and the available nodes

#### My Setup
kube-vip: v0.8.0 as static pod
on Ubuntu 24.04.2 LTS VMs
kubernetes: v1.32.0

----------------------------------
#### after failover (and starting the node again i.e. currently active nodes are 3)
`ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.2.223:6443              Masq    1      9          0
  -> 10.0.3.237:6443              Masq    1      13         0
```

`kubectl logs kube-vip-vm3-private -n kube-system`
```
time="2025-03-01T11:36:59Z" level=info msg="Node [vm3-private] is assuming leadership of the cluster"
time="2025-03-01T11:36:59Z" level=info msg="Starting IPVS LoadBalancer"
time="2025-03-01T11:36:59Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2025-03-01T11:36:59Z" level=info msg="sysctl set net.ipv4.vs.conntrack to 1"
time="2025-03-01T11:36:59Z" level=info msg="sysctl set net.ipv4.ip_forward to 1"
time="2025-03-01T11:36:59Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [10.1.0.0/ens5]"
time="2025-03-01T11:36:59Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2025-03-01T11:36:59Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": dial tcp 10.0.4.86:6443: connect: connection refused"
time="2025-03-01T11:36:59Z" level=error msg="Error querying backends file does not exist"
time="2025-03-01T11:36:59Z" level=info msg="Created Load-Balancer services on [10.1.0.0:6443]"
time="2025-03-01T11:36:59Z" level=info msg="Added backend for [10.1.0.0:6443] on [10.0.3.237:6443]"
time="2025-03-01T11:36:59Z" level=info msg="Added backend for [10.1.0.0:6443] on [10.0.2.223:6443]"
time="2025-03-01T11:37:14Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:37:29Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:37:44Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:37:59Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:38:14Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:38:29Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:38:44Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:38:59Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:39:14Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:39:29Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2025-03-01T11:39:34Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": dial tcp 10.0.4.86:6443: connect: connection refused"
time="2025-03-01T11:39:39Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": dial tcp 10.0.4.86:6443: connect: connection refused"
time="2025-03-01T11:39:44Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": dial tcp 10.0.4.86:6443: connect: connection refused"
time="2025-03-01T11:39:49Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": dial tcp 10.0.4.86:6443: connect: connection refused"
time="2025-03-01T11:39:54Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": dial tcp 10.0.4.86:6443: connect: connection refused"
time="2025-03-01T11:39:59Z" level=info msg="failed check k8s server version: Get \"https://10.0.4.86:6443/version?timeout=10s\": dial tcp 10.0.4.86:6443: connect: connection refused"
time="2025-03-01T11:40:06Z" level=info msg="failed check k8s server version: unknown"
```

####  **all nodes added** after manually stopping with `crictl stop <kube-vip container id>`

`ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.2.223:6443              Masq    1      9          0
  -> 10.0.3.237:6443              Masq    1      13         0
  -> 10.0.4.86:6443               Masq    1      0          0
```

` kubectl logs kube-vip-vm3-private -n kube-system`
```
time="2025-03-01T11:46:25Z" level=info msg="Starting kube-vip.io [v0.8.0]"
time="2025-03-01T11:46:25Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2025-03-01T11:46:25Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2025-03-01T11:46:25Z" level=info msg="prometheus HTTP server started"
time="2025-03-01T11:46:25Z" level=info msg="kube-vip will bind to interface [ens5]"
time="2025-03-01T11:46:25Z" level=info msg="Using node name [vm3-private]"
time="2025-03-01T11:46:25Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2025-03-01T11:46:25Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [vm3-private]"
I0301 11:46:25.184965       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
I0301 11:46:25.207459       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-cp-lock
time="2025-03-01T11:46:25Z" level=info msg="Node [vm3-private] is assuming leadership of the cluster"
time="2025-03-01T11:46:25Z" level=info msg="Starting IPVS LoadBalancer"
time="2025-03-01T11:46:25Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2025-03-01T11:46:25Z" level=info msg="sysctl set net.ipv4.vs.conntrack to 1"
time="2025-03-01T11:46:25Z" level=info msg="sysctl set net.ipv4.ip_forward to 1"
time="2025-03-01T11:46:25Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [10.1.0.0/ens5]"
time="2025-03-01T11:46:25Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2025-03-01T11:46:25Z" level=info msg="Added backend for [10.1.0.0:6443] on [10.0.4.86:6443]"
```
----------------------------------
#### kube-vip.yml manifest file
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-vip
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "True"
    - name: port
      value: "6443"
    - name: vip_nodename
      value: vm1-private
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: "first"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "False"
	- name: cp_detect
      value: "False"
    - name: svc_leasename
      value: "plndr-svcs-lock"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: "plndr-cp-lock"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: "10.1.0.0"
    - name: lb_enable
      value: "true"
    - name: lb_fwdmethod
      value: "masquerade"
    image: ghcr.io/kube-vip/kube-vip-iptables:v0.8.0
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Comment by Cellebyte** [comment]
Can you try the latest version?

**Comment by aviral-agarwal** [comment]
Hey @Cellebyte,

Thanks for taking note

Unfortunately, the same behaviour with the latest version of kube-vip

### My Setup

kube-vip: v0.8.9 as static pod
on Ubuntu 24.04.2 LTS VMs
kubernetes: v1.32.0

**following is being done on leader node**

----------------------------------------
### after initial setup, no failover yet
`ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.3.31:6443               Masq    1      22         0
TCP  10.233.0.1:443 rr
  -> 10.0.2.47:6443               Masq    1      3          0
  -> 10.0.3.31:6443               Masq    1      0          0
  -> 10.0.4.77:6443               Masq    1      2          0
```

*for reference, note the internal IPVS Virtual service for 10.233.0.1:443 (corresponding to **kubernetes** Cluster IP service managed by kube-proxy*, 
it has all the control plane nodes and detects them as expected on failover or addition of new control plane node
`kubectl get services --all-namespaces`
```
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP                  24m
kube-system   coredns      ClusterIP   10.233.0.3   <none>        53/UDP,53/TCP,9153/TCP   22m
```


`kubectl logs kube-vip-vm1-private -n kube-system`
```
time="2025-03-02T05:59:47Z" level=info msg="Starting kube-vip.io [v0.8.9]"
time="2025-03-02T05:59:47Z" level=info msg="Build kube-vip.io [19e660d4a692fab29f407214b452f48d9a65425e]"
time="2025-03-02T05:59:47Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2025-03-02T05:59:47Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2025-03-02T05:59:47Z" level=info msg="prometheus HTTP server started"
time="2025-03-02T05:59:47Z" level=info msg="kube-vip will bind to interface [ens5]"
time="2025-03-02T05:59:47Z" level=info msg="Using node name [vm1-private]"
time="2025-03-02T05:59:47Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2025-03-02T05:59:47Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [vm1-private]"
I0302 05:59:47.587264       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2025-03-02T05:59:47Z" level=info msg="Starting UPNP Port Refresher"
I0302 05:59:51.901314       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-cp-lock
time="2025-03-02T05:59:51Z" level=info msg="Node [vm1-private] is assuming leadership of the cluster"
time="2025-03-02T05:59:52Z" level=info msg="Starting IPVS LoadBalancer"
time="2025-03-02T05:59:52Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2025-03-02T05:59:52Z" level=info msg="sysctl set net.ipv4.vs.conntrack to 1"
time="2025-03-02T05:59:52Z" level=info msg="sysctl set net.ipv4.ip_forward to 1"
time="2025-03-02T05:59:52Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [10.1.0.0/ens5]"
time="2025-03-02T05:59:52Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2025-03-02T05:59:54Z" level=error msg="Error querying backends file does not exist"
time="2025-03-02T05:59:54Z" level=info msg="Created Load-Balancer services on [10.1.0.0:6443]"
time="2025-03-02T05:59:54Z" level=info msg="Added backend for [10.1.0.0:6443] on [10.0.3.31:6443]"
time="2025-03-02T06:00:09Z" level=error msg="failed check k8s server version: Get \"https://10.0.2.47:6443/version?timeout=10s\": dial tcp 10.0.2.47:6443: connect: connection refused"
time="2025-03-02T06:04:47Z" level=info msg="[UPNP] Refreshing 0 Instances"
time="2025-03-02T06:09:47Z" level=info msg="[UPNP] Refreshing 0 Instances"
time="2025-03-02T06:14:47Z" level=info msg="[UPNP] Refreshing 0 Instances"
time="2025-03-02T06:19:47Z" level=info msg="[UPNP] Refreshing 0 Instances"
```
----------------------------------------

### after forcing the kube-vip pod to restart

Again, all nodes are added after manually stopping the kube-vip container with `crictl stop <kube-vip container id>` 
As expected, since kube-vip is running as a static pod, kubelet will restart the pod immediately

`ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.2.47:6443               Masq    1      0          0
  -> 10.0.3.31:6443               Masq    1      22         0
  -> 10.0.4.77:6443               Masq    1      0          0
TCP  10.233.0.1:443 rr
  -> 10.0.2.47:6443               Masq    1      3          0
  -> 10.0.3.31:6443               Masq    1      0          0
  -> 10.0.4.77:6443               Masq    1      2          0
```
`kubectl logs kube-vip-vm1-private -n kube-system`
*observe, no errors in kube-vip pod logs after forced restart/crictl stop*
```
time="2025-03-02T06:30:33Z" level=info msg="Starting kube-vip.io [v0.8.9]"
time="2025-03-02T06:30:33Z" level=info msg="Build kube-vip.io [19e660d4a692fab29f407214b452f48d9a65425e]"
time="2025-03-02T06:30:33Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2025-03-02T06:30:33Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2025-03-02T06:30:33Z" level=info msg="prometheus HTTP server started"
time="2025-03-02T06:30:33Z" level=info msg="kube-vip will bind to interface [ens5]"
time="2025-03-02T06:30:33Z" level=info msg="Using node name [vm1-private]"
time="2025-03-02T06:30:33Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2025-03-02T06:30:33Z" level=info msg="Starting UPNP Port Refresher"
time="2025-03-02T06:30:33Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [vm1-private]"
I0302 06:30:33.563853       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
I0302 06:30:33.625145       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-cp-lock
time="2025-03-02T06:30:33Z" level=info msg="Node [vm1-private] is assuming leadership of the cluster"
time="2025-03-02T06:30:33Z" level=info msg="Starting IPVS LoadBalancer"
time="2025-03-02T06:30:33Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2025-03-02T06:30:33Z" level=info msg="sysctl set net.ipv4.vs.conntrack to 1"
time="2025-03-02T06:30:33Z" level=info msg="sysctl set net.ipv4.ip_forward to 1"
time="2025-03-02T06:30:33Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [10.1.0.0/ens5]"
time="2025-03-02T06:30:33Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2025-03-02T06:30:33Z" level=info msg="Added backend for [10.1.0.0:6443] on [10.0.2.47:6443]"
time="2025-03-02T06:30:33Z" level=info msg="Added backend for [10.1.0.0:6443] on [10.0.4.77:6443]"
```
----------------------------------------
### kube-vip.yml manifest file
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-vip
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "True"
    - name: port
      value: "6443"
    - name: vip_nodename
      value: vm1-private
    - name: vip_cidr
	  value: "32"
    - name: dns_mode
      value: "first"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "False"
    - name: cp_detect
      value: "False"
    - name: svc_leasename
      value: "plndr-svcs-lock"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: "plndr-cp-lock"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: "10.1.0.0"
    - name: lb_enable
      value: "true"
    - name: lb_fwdmethod
      value: "masquerade"
	image: ghcr.io/kube-vip/kube-vip-iptables:v0.8.9
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Comment by Cloud-Mak** [comment]
Just bumping this in anticipation that someone from dev team here pick this up.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @Cloud-Mak 

I've just created a PR that should fix this issue.
You can test this with my image or wait for an official release:

```
ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-fix
```

**Comment by Cellebyte** [comment]
@Cloud-Mak yes it is still the case for newer k8s releases.

**Comment by aviral-agarwal** [comment]
Hi all,

I was able to test the following image by @p-strusiewiczsurmacki-mobica 
```
ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-fix
```
and it does solve the IPVS issue. **Thank you**


However, while testing, I stumbled upon the following 
## edge case/issue

#### Description
* Disrupting kube-vip pod on leader leads to new leader election which is not an issue (for me at least)
* and the new leader has correct backends for the control plane load balancing IPVS service (which was the issue earlier), 
* But the old leader (where kube-vip pod was disrupted) continues to have the IPVS virtual service for kube-vip Virtual IP
* Note: the kube-vip pod restarts successfully on the old leader. But the IPVS service continues to exist
* I had **observed this with the original image as well** but believed this may be related to the now solved IPVS issues.

#### My guess on why this may be happening and a possible fix?
* Because kube-vip pod was disrupted, it could not remove the IPVS service
* Checking and enforcing the IPVS service on kube-vip pod start will handle this edge case and will definitely **make kube-vip more robust.** 
* **Else, I will have to make arrangements to check for this in case of a failover**

-------------------------------------------------
#### for reference: logs/how to reproduce
* 3 control plane nodes: vm1, vm2, vm3
* initial leader was `vm2` and had IPVS service as expected, I don't have logs for that
* disrupted kube-vip pod on `vm2` by making changes in `image` of `kube-vip.yml`

* kube-vip pod restarted successfully after destruction on `vm2`
`kubectl logs kube-vip-vm2-private -n kube-system`
```
2025/03/05 12:26:17 INFO kube-vip.io version=v0.8.10-ipvs-fix build=2dfd46decb57be08846fcad89d11353dfa26a6f7
2025/03/05 12:26:17 INFO starting namespace=kube-system Mode=ARP "Control Plane"=true Services=false
2025/03/05 12:26:17 INFO No interface is specified for VIP in config, auto-detecting default Interface
2025/03/05 12:26:17 INFO kube-vip bind interface=ens5
2025/03/05 12:26:17 INFO using node name name=vm2-private
2025/03/05 12:26:17 INFO prometheus HTTP server started
2025/03/05 12:26:17 INFO Starting Kube-vip Manager with the ARP engine
2025/03/05 12:26:17 INFO cluster membership namespace=kube-system lock=plndr-cp-lock id=vm2-private
2025/03/05 12:26:17 INFO Starting UPNP Port Refresher
I0305 12:26:17.675361       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
2025/03/05 12:26:17 INFO New leader leader=vm1-private
2025/03/05 12:31:17 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:36:17 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:41:17 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:46:17 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:51:17 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:56:17 INFO [UPNP] Refreshing Instances "number of instances"=0
```
* new leader election takes place on kube-vip pod disruption on the old leader `vm2`
* and `vm1` is the new elected leader **timestamp: 12:26:06**
`kubectl logs kube-vip-vm1-private -n kube-system`
```
2025/03/05 12:20:20 INFO kube-vip.io version=v0.8.10-ipvs-fix build=2dfd46decb57be08846fcad89d11353dfa26a6f7
2025/03/05 12:20:20 INFO starting namespace=kube-system Mode=ARP "Control Plane"=true Services=false
2025/03/05 12:20:20 INFO No interface is specified for VIP in config, auto-detecting default Interface
2025/03/05 12:20:20 INFO prometheus HTTP server started
2025/03/05 12:20:20 INFO kube-vip bind interface=ens5
2025/03/05 12:20:20 INFO using node name name=vm1-private
2025/03/05 12:20:20 INFO Starting Kube-vip Manager with the ARP engine
2025/03/05 12:20:20 INFO Starting UPNP Port Refresher
2025/03/05 12:20:20 INFO cluster membership namespace=kube-system lock=plndr-cp-lock id=vm1-private
I0305 12:20:20.476111       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
2025/03/05 12:20:20 INFO New leader leader=vm3-private
2025/03/05 12:21:39 INFO New leader leader=vm2-private
2025/03/05 12:25:20 INFO [UPNP] Refreshing Instances "number of instances"=0
I0305 12:26:06.120828       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-cp-lock
2025/03/05 12:26:06 INFO New leader leader=vm1-private
2025/03/05 12:26:06 INFO Starting IPVS LoadBalancer
2025/03/05 12:26:06 INFO IPVS Loadbalancer enabled version=" 1.2.1"
2025/03/05 12:26:06 INFO sysctl set net.ipv4.vs.conntrack to 1
2025/03/05 12:26:06 INFO sysctl set net.ipv4.ip_forward to 1
2025/03/05 12:26:06 INFO layer 2 broadcaster starting
2025/03/05 12:26:06 INFO Kube-Vip is watching nodes for control-plane labels
2025/03/05 12:26:06 ERROR querying backends err="file does not exist"
2025/03/05 12:26:06 INFO load-Balancer services created address=10.1.0.0 port=6443
2025/03/05 12:26:06 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.3.183 "dst port"=6443
2025/03/05 12:26:06 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.4.58 "dst port"=6443
2025/03/05 12:26:06 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.2.227 "dst port"=6443
2025/03/05 12:30:20 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:35:20 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:40:20 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:45:20 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/05 12:50:20 INFO [UPNP] Refreshing Instances "number of instances"=0
```
* as expected, IPVS Virtual service is correctly created on the new leader `vm1`
`ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.2.227:6443              Masq    1      8          0
  -> 10.0.3.183:6443              Masq    1      5          0
  -> 10.0.4.58:6443               Masq    1      4          0
TCP  10.233.0.1:443 rr
  -> 10.0.2.227:6443              Masq    1      0          0
  -> 10.0.3.183:6443              Masq    1      3          0
  -> 10.0.4.58:6443               Masq    1      1          0
```
*  but IPVS Virtual service on the old leader `vm2` continues to exist
`ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.3.183:6443              Masq    1      5          0
  -> 10.0.4.58:6443               Masq    1      0          0
TCP  10.233.0.1:443 rr
  -> 10.0.2.227:6443              Masq    1      0          0
  -> 10.0.3.183:6443              Masq    1      1          0
  -> 10.0.4.58:6443               Masq    1      5          0
```
#### Note:
* When I forced `vm2` to become leader again 
* Then instead of disrupting the kube-vip pod, properly shut the machine down, a new leader was naturally elected
* but this time, the IPVS service on the old leader `vm2` was properly cleared

**Comment by p-strusiewiczsurmacki-mobica** [comment]
> [@p-strusiewiczsurmacki-mobica](https://github.com/p-strusiewiczsurmacki-mobica)
> I wonder why its going to default repo for kube-vip image inspite of mentioning your image URL in alias. I could see your container image got downloaded on node (23MB size)

@Cloud-Mak Image name used in `kubevip manifest` command is hardcoded to `ghcr.io/kube-vip/kube-vip` so you'd have to manually change it to `ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables` in the generated ` /etc/kubernetes/manifests/kube-vip.yaml`.

@aviral-agarwal Thank you for the detailed description. I'll look into this as soon as possible!

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @aviral-agarwal

Could you maybe test this one, please? If I understand the issue correctly, it should help for the IPVS deletion, I think.

```
ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v1
```

**Comment by aviral-agarwal** [comment]
Hey @p-strusiewiczsurmacki-mobica 

Thanks for looking into it
I tested the image `ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v1` 
**Unfortunately, the issue persists**

### My Setup

kube-vip: image as mentioned, as static pod
on 3 Ubuntu 24.04.2 LTS VMs, `vm1`, `vm2`m `vm3` control planes
kubernetes: v1.32.2


### Steps followed/issue

* after initial setup, `vm1` is the leader and has expected IPVS service for kube-vip VIP `10.1.0.0`
* I disrupted kube-vip pod on the initial/current leader `vm1` by adding a new line at the end in `/etc/kubernetes/manifest/kube-vip.yml` kube-vip manifest file
* after disruption, leader election takes place and `vm3` is elected leader
* meanwhile, on `vm1`, kube-vip pod starts again
* but the IPVS virtual service initially created  on `vm1` (when it was leader, before disruption) persists even after VIP switching over to `vm3`

### for reference, logs after disruption

after disrupting kube-vip on initial leader `vm1`, a new leader `vm3` is elected 

`root@vm3-private:~# kubectl logs kube-vip-vm3-private -n kube-system`
```
2025/03/11 09:36:50 INFO kube-vip.io version=v0.8.10-ipvs-deletion-fix-v1 build=8ffb9aae9a605906bb5dd4c588a83b6ef0f06f54
2025/03/11 09:36:50 INFO starting namespace=kube-system Mode=ARP "Control Plane"=true Services=false
2025/03/11 09:36:50 INFO No interface is specified for VIP in config, auto-detecting default Interface
2025/03/11 09:36:50 INFO kube-vip bind interface=ens5
2025/03/11 09:36:50 INFO prometheus HTTP server started
2025/03/11 09:36:50 INFO using node name name=vm3-private
2025/03/11 09:36:50 INFO Starting Kube-vip Manager with the ARP engine
2025/03/11 09:36:50 INFO cluster membership namespace=kube-system lock=plndr-cp-lock id=vm3-private
I0311 09:36:50.388074       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
2025/03/11 09:36:50 INFO Starting UPNP Port Refresher
E0311 09:36:55.904186       1 leaderelection.go:436] error retrieving resource lock kube-system/plndr-cp-lock: leases.coordination.k8s.io "plndr-cp-lock" is forbidden: User "kubernetes-admin" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system": RBAC: [clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "cluster-admin" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found, clusterrole.rbac.authorization.k8s.io "system:public-info-viewer" not found]
2025/03/11 09:36:57 INFO New leader leader=vm1-private
2025/03/11 09:41:50 INFO [UPNP] Refreshing Instances "number of instances"=0
I0311 09:46:46.665658       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-cp-lock
2025/03/11 09:46:46 INFO New leader leader=vm3-private
2025/03/11 09:46:46 INFO Starting IPVS LoadBalancer
2025/03/11 09:46:46 INFO IPVS Loadbalancer enabled version=" 1.2.1"
2025/03/11 09:46:46 INFO sysctl set net.ipv4.vs.conntrack to 1
2025/03/11 09:46:46 INFO sysctl set net.ipv4.ip_forward to 1
2025/03/11 09:46:46 INFO layer 2 broadcaster starting
2025/03/11 09:46:46 INFO Kube-Vip is watching nodes for control-plane labels
2025/03/11 09:46:46 ERROR querying backends err="file does not exist"
2025/03/11 09:46:46 INFO load-Balancer services created address=10.1.0.0 port=6443
2025/03/11 09:46:46 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.4.93 "dst port"=6443
2025/03/11 09:46:47 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.2.41 "dst port"=6443
2025/03/11 09:46:47 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.3.206 "dst port"=6443
2025/03/11 09:46:50 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/11 09:51:50 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/11 09:56:50 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/11 10:01:50 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/11 10:06:50 INFO [UPNP] Refreshing Instances "number of instances"=0
```
and IPVS service for kube-vip VIP `10.1.0.0` is created as expected on `vm3`
`root@vm3-private:~# ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.2.41:6443               Masq    1      3          0
  -> 10.0.3.206:6443              Masq    1      7          0
  -> 10.0.4.93:6443               Masq    1      7          0
TCP  10.233.0.1:443 rr
  -> 10.0.2.41:6443               Masq    1      0          0
  -> 10.0.3.206:6443              Masq    1      4          0
  -> 10.0.4.93:6443               Masq    1      1          0
```
But, on `vm1` IPVS service for kube-vip VIP `10.1.0.0` continues to exist despite `vm3` being the new leader

`root@vm1-private:/etc/kubernetes/manifests# ipvsadm -Ln`
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.1.0.0:6443 rr
  -> 10.0.2.41:6443               Masq    1      6          0
  -> 10.0.3.206:6443              Masq    1      7          0
  -> 10.0.4.93:6443               Masq    1      10         0
TCP  10.233.0.1:443 rr
  -> 10.0.2.41:6443               Masq    1      1          0
  -> 10.0.3.206:6443              Masq    1      2          0
  -> 10.0.4.93:6443               Masq    1      2          0
```

the kube-vip pod successfully starts on the initial leader `vm1`
**suggestion: maybe at this point, it should be checked if an IPVS service for VIP is there and should be removed if the machine is not the leader**
`root@vm1-private:/etc/kubernetes/manifests# kubectl logs kube-vip-vm1-private -n kube-system`
```
2025/03/11 09:47:48 INFO kube-vip.io version=v0.8.10-ipvs-deletion-fix-v1 build=8ffb9aae9a605906bb5dd4c588a83b6ef0f06f54
2025/03/11 09:47:48 INFO starting namespace=kube-system Mode=ARP "Control Plane"=true Services=false
2025/03/11 09:47:48 INFO No interface is specified for VIP in config, auto-detecting default Interface
2025/03/11 09:47:48 INFO prometheus HTTP server started
2025/03/11 09:47:48 INFO kube-vip bind interface=ens5
2025/03/11 09:47:48 INFO using node name name=vm1-private
2025/03/11 09:47:48 INFO Starting Kube-vip Manager with the ARP engine
2025/03/11 09:47:48 INFO cluster membership namespace=kube-system lock=plndr-cp-lock id=vm1-private
2025/03/11 09:47:48 INFO Starting UPNP Port Refresher
I0311 09:47:48.064020       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
2025/03/11 09:47:48 INFO New leader leader=vm3-private
2025/03/11 09:52:48 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/11 09:57:48 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/11 10:02:48 INFO [UPNP] Refreshing Instances "number of instances"=0
```

### yaml manifest kube-vip.yml

```
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-vip
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "True"
    - name: port
      value: "6443"
    - name: vip_nodename
      value: vm1-private
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: "first"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "False"
    - name: cp_detect
      value: "False"
    - name: svc_leasename
      value: "plndr-svcs-lock"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: "plndr-cp-lock"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: "10.1.0.0"
    - name: lb_enable
      value: "true"
    - name: lb_fwdmethod
      value: "masquerade"
    image: ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v1
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/super-admin.conf
    name: kubeconfig
status: {}
```

**Comment by Cellebyte** [comment]
We should rebuild the image with the endpoint and service watcher fix in main.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
@aviral-agarwal I've tried to reproduce this but for me IPVS is removed every time I alter the static pod's manifest. Could you maybe try to 

1. Add debug logging to the pods:
```
env:
- name: vip_loglevel
  value: "-4"
```
2. Get the logs from the leader pod with `kubectl logs ... --follow`, then alter the pod and paste the full log here? I'd like to check what is happening inside the pod after it's altered and IPVS is not deleted, but as I said I can't reproduce this on my setup.

**Comment by aviral-agarwal** [comment]
Hey @p-strusiewiczsurmacki-mobica 

I tested with the new image and with the env for logs in manifest yaml as you suggested

* For disrupting the kube-vip pod, I only changed the kube-vip.yml manifest
* The IPVS service was removed sometime, but not consitently
* in logs, sometimes, I could see 
`INFO Stopping IPVS LoadBalancer` 
when disruption took place and those times IPVS services is successfully removed
* but other times, I could only see 
```
2025/03/12 06:00:03 INFO Received termination, signaling cluster shutdown
2025/03/12 06:00:03 INFO Shutting down Kube-Vip
```
after disruption
* but whether IPVS is removed can only be verified with `ipvsadm -Ln`
* when logs explicitly says, `Stopping IPVS LoadBalancer` IPVS was actually removed. In other cases, not always

### for reference, logs after disruption
on leader nodes and kube-vip is `10.1.0.0`


`vm3` was leader and kube-vip pod was disrupted after adding a blank line at the end of `kube-vip.yml` manifest
as you can see, `vm2` was elected leader after disruption 
but IPVS remained on `vm3`
![Image](https://github.com/user-attachments/assets/10a63b0d-3c92-4345-adee-0b641a2d999e)


one more incident, same result
`vm2` was leader and kube-vip pod was disrupted after adding a blank line at the end of `kube-vip.yml` manifest
as you can see, `vm3` was elected leader after disruption 
but IPVS remained on `vm2`
![Image](https://github.com/user-attachments/assets/d7228fc3-6d21-4d5a-b254-a3fceae6f0f2)

`vm1` was leader and kube-vip pod was disrupted after adding a blank line at the end of `kube-vip.yml` manifest
as you can see, `vm2` was elected leader after disruption 
but IPVS remained on `vm1`
![Image](https://github.com/user-attachments/assets/ab37e8b2-d00d-4413-a018-f3db6e0198d0)

log when I got explicit message of removing IPVS
```
root@vm3-private:~# kubectl logs kube-vip-vm3-private -n kube-system --follow
2025/03/12 05:25:05 INFO kube-vip.io version=v0.8.10-ipvs-deletion-fix-v2 build=8ffb9aae9a605906bb5dd4c588a83b6ef0f06f54
2025/03/12 05:25:05 INFO starting namespace=kube-system Mode=ARP "Control Plane"=true Services=false
2025/03/12 05:25:05 INFO No interface is specified for VIP in config, auto-detecting default Interface
2025/03/12 05:25:05 INFO kube-vip bind interface=ens5
2025/03/12 05:25:05 INFO prometheus HTTP server started
2025/03/12 05:25:05 INFO using node name name=vm3-private
2025/03/12 05:25:05 INFO Starting Kube-vip Manager with the ARP engine
2025/03/12 05:25:05 INFO cluster membership namespace=kube-system lock=plndr-cp-lock id=vm3-private
I0312 05:25:05.720217       1 leaderelection.go:257] attempting to acquire leader lease kube-system/plndr-cp-lock...
2025/03/12 05:25:05 INFO Starting UPNP Port Refresher
2025/03/12 05:25:09 INFO New leader leader=vm1-private
2025/03/12 05:30:05 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/12 05:33:50 INFO New leader leader=vm2-private
2025/03/12 05:35:05 INFO [UPNP] Refreshing Instances "number of instances"=0
I0312 05:39:37.497513       1 leaderelection.go:271] successfully acquired lease kube-system/plndr-cp-lock
2025/03/12 05:39:37 INFO New leader leader=vm3-private
2025/03/12 05:39:37 INFO Starting IPVS LoadBalancer
2025/03/12 05:39:37 INFO IPVS Loadbalancer enabled version=" 1.2.1"
2025/03/12 05:39:37 INFO sysctl set net.ipv4.vs.conntrack to 1
2025/03/12 05:39:37 INFO sysctl set net.ipv4.ip_forward to 1
2025/03/12 05:39:37 INFO layer 2 broadcaster starting
2025/03/12 05:39:37 INFO Kube-Vip is watching nodes for control-plane labels
2025/03/12 05:39:37 ERROR querying backends err="file does not exist"
2025/03/12 05:39:37 INFO load-Balancer services created address=10.1.0.0 port=6443
2025/03/12 05:39:37 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.4.236 "dst port"=6443
2025/03/12 05:39:37 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.2.136 "dst port"=6443
2025/03/12 05:39:37 INFO backend added "src addr"=10.1.0.0 "src port"=6443 "dst addr"=10.0.3.86 "dst port"=6443
2025/03/12 05:40:05 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/12 05:45:05 INFO [UPNP] Refreshing Instances "number of instances"=0
2025/03/12 05:49:47 INFO Stopping IPVS LoadBalancer
```

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @aviral-agarwal 

Thank you for the logs! Those are extremely helpful to be honest! I think I know where the problem is and added some changes. Could you please test with this image? Sorry to bother you!

```
ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v3
```

**Comment by aviral-agarwal** [comment]
Hey @p-strusiewiczsurmacki-mobica 
No worries and happy to help

also happy to inform that I couldn't reproduce the error with this image
`ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v3`

I am going to use this one for now, and I presume this fix is going to make its way to a subsequent release

Thank you once again

**Comment by Cloud-Mak** [comment]
Hi all,

1st para I mentiond in 1st most post - After you create multimaster cluster (3 nodes min), the ipvs service on 1st most master shows only 1st node in backend. Once the new leader is elected then only all master nodes appears in background. I have tested this today and its still the case even with latest image @p-strusiewiczsurmacki-mobica shared.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @Cloud-Mak
I've deployed your config and I think I have finally fixed the issue. Can you please test with this image?

```
ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v4

or

ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip:v0.8.10-ipvs-deletion-fix-v4

```

**Comment by Cloud-Mak** [comment]
> Hi [@Cloud-Mak](https://github.com/Cloud-Mak) I've deployed your config and I think I have finally fixed the issue. Can you please test with this image?
> 
> ```
> ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v4
> 
> or
> 
> ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip:v0.8.10-ipvs-deletion-fix-v4
> ```

Perfect. I tested new image successfully. Thanks @p-strusiewiczsurmacki-mobica 


```
Every 2.0s: incus exec x-master1 -- ipvsadm -l                                                                                   bknd-master1: Mon Mar 17 17:14:14 2025

IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  x-master1:6443 rr
  -> x-master2.incus:6443         Local   1      3          0
  -> x-master1.incus:6443         Local   1      2          0
  -> x-master3.incus:6443         Local   1      0          0
```

**Comment by a-haurylau** [comment]
Tested this one as well. @p-strusiewiczsurmacki-mobica  - many kudos :)

Few comments about kube-vip logic for control plane HA (as this is not documented/I did not find that in docs):
1. Current behaviour (0.8.9): control plane health-check are performed only in ipvs mode with masquerade enabled. With [this PR](https://github.com/kube-vip/kube-vip/pull/1096) logic changed that health-checks are performed in any ipvs mode (local, direct-routing etc). But still without IPVS - no health-checks.
1.1. When you disable ipvs (so no loadbalancer flag) when running kube-vip-iptables image MASQUERADE rule with -m ipvs is still added (so at ipvsadm no rules, but in FW we still have that).
3.  There is one corner-case that is not covered by PR mentioned: when api server is DOWN on same node as CP VIP address and CP VIP address is in a same network as API servers addresses. In this case in mode: local everything is broken. In order for this to work - we must change to masquerade mode again, use kube-vip-iptables image instead of default one and run this image in privilege mode. I think this needs to be documented.
3.1. Privilege mode is needed for setting 2 non namespaced OS sysctls (ip_forward and conntrack). For that part - it will be really nice that in ipvs.go check on those sysctl is performed first (instead of just setting) and if value is OK (set to 1) - everything is OK. If its not set: log message emits that suggest set it in OS level or run pod as privileged.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @a-haurylau , thank you for your kind words! :)

>     1. Current behaviour (0.8.9): control plane health-check are performed only in ipvs mode with masquerade enabled. With [this PR](https://github.com/kube-vip/kube-vip/pull/1096) logic changed that health-checks are performed in any ipvs mode (local, direct-routing etc). Without IPVS - no health-checks.

That's right. I do not see any reason to not perform healthcheck in every mode, but if anyone is aware of such a reason please just share it and I'll try to fix that.

>     2. When you disable ipvs (so no loadbalancer flag) when running kube-vip-iptables image MASQUERADE rule with -m ipvs is still added (so at ipvsadm no rules, but in FW we still have that).

Are you sure those are not some old rules that were not removed? According to the code no `-m ipvs` rules should be added in modes other than `masquerade`. Or am I missing something?

>     3. There is one corner-case that is not covered by PR mentioned: when api server is DOWN on same node as CP VIP address and CP VIP address is in a same network as API servers addresses. In this case in mode: local everything is broken. In order for this to work - we must change to masquerade mode again, use kube-vip-iptables image instead of default one and run this image in privilege mode. I think this needs to be documented.

I'll try to reproduce that and confirm that behaviour.

>     4. Privilege mode is needed for setting 2 non namespaced OS sysctls (ip_forward and conntrack). For that part - it will be really nice that in ipvs.go check on those sysctl is performed first (instead of just setting) and if value is OK (set to 1) - everything is OK. If its not set: log message emits that suggest set it in OS level or run pod as privileged.

I've added this check to the mentioned PR.

**Comment by a-haurylau** [comment]
> Are you sure those are not some old rules that were not removed? According to the code no -m ipvs rules should be added in modes other than masquerade. Or am I missing something?
Hmm. I've checked like this:
Flags: --controlplane --enableLoadBalancer - using iptables image -> rule -m ipvs was added (regardless of LB mode)
Flags: --controlplane - using iptables image -> rule is also added. But I expect that here we not using loadbalancing, so no rules should be added in firewall.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
> > Are you sure those are not some old rules that were not removed? According to the code no -m ipvs rules should be added in modes other than masquerade. Or am I missing something?
> 
> Hmm. I've checked like this: Flags: --controlplane --enableLoadBalancer - using iptables image -> rule -m ipvs was added (regardless of LB mode) Flags: --controlplane - using iptables image -> rule is also added. But I expect that here we not using loadbalancing, so no rules should be added in firewall.

That's weird, really. I've just checked with clean kind setup and for me the rule `-A POSTROUTING -m ipvs --vaddr 172.18.10.10 -m comment --comment "172.18.10.10 kube-vip load balancer IP" -j MASQUERADE` is only created if LB is enabled and mode is `masquerade`. Even if LB is enabled but in `local` mode, the rule is not created.

**Comment by Cellebyte** [comment]
@p-strusiewiczsurmacki-mobica I think having a healthcheck in every mode is fine. And only healthy endpoints can take leadership if leader election is configured.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
> 3\. There is one corner-case that is not covered by PR mentioned: when api server is DOWN on same node as CP VIP address and CP VIP address is in a same network as API servers addresses. In this case in mode: local everything is broken. In order for this to work - we must change to masquerade mode again, use kube-vip-iptables image instead of default one and run this image in privilege mode. I think this needs to be documented.

I am investigating this right now. It seems that if forwarding method is set to `local` IPVS only uses local endpoint (so no loadbalancing is performed) and packets are not routed to external endpoints. Only thing that comes to my mind to fix this is to step down from leaderelection if no local endpoint is healthy.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
@a-haurylau I think I've fixed number 3. Could you please check with one of those images if the problem was fixed for you?

```
ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip-iptables:v0.8.10-ipvs-deletion-fix-v5
ghcr.io/p-strusiewiczsurmacki-mobica/kube-vip:v0.8.10-ipvs-deletion-fix-v5
```

If forwarding method is set to `local` kube-vip should now cancel leaderelection if no local endpoints are present.

**Comment by maxisam** [comment]
I tested v5, I think it fixed my issues as well. 

I have lb_enable on cp but not service + "Masquerade" + cilium l2 announcement.

**Comment by maxisam** [comment]
I also wanna double check this, so when I run `arping -I ${net_interface} -c 3 -w 10 ${vip}` on cp nodes

I can see each of them got replied from the other 2 nodes.

And I can see vip on each node as well with `ip addr | grep ${vip}`

and the ipvs -ln on the leader node is like

![Image](https://github.com/user-attachments/assets/862ed6b1-7cf0-4c30-b866-00cb479c9f5a)


I guess this works as expect with ipvs load balancer on cp nodes with masquerade?

**Comment by Cellebyte** [comment]
Did anyone tested the IPv6 codepath yet?

**Comment by Cellebyte** [comment]
@maxisam could you test the latest changes from the PullRequest if they still solve the issue, as @p-strusiewiczsurmacki-mobica added IPv6 support and I want to make sure we don’t introduce a regression because of that.

**Comment by maxisam** [comment]
Is it like v6?

**Comment by Cellebyte** [comment]
@maxisam sorry I did not get your point.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
@maxisam Could you please share your kube-vip's deployment/config?

**Comment by maxisam** [comment]
with v6, i got ipvs rules on the leader node correctly 

![Image](https://github.com/user-attachments/assets/c82b092e-6597-46d7-9fb3-70098c16d81c)

and vip only shows up on the leader node

And both non leader nodes got arping response from the leader node only

**Comment by Cellebyte** [comment]
@maxisam thanks for validating the ipv4 codepath again :)
The next release will have this fix in it.
I am preparing for a new release.

**Comment by maxisam** [comment]
Something weird happened. 

It seems like it is always timeout when I try to connect to the vip after I upgraded kube-vip to v0.8.10 with "lb_fwdmethod=masquerade" , it does work with "lb_fwdmethod=local".

But it was working with v6 when I tested it.  I don't have to use masquerade, but it is something others might want to verify.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @maxisam 

Thank you for the info! I have just deployed v0.8.10 on both IPv4-only and dualstack cluster, and IPv4 IPVS (masquereda) works for me on both. So I think we will need to wait for more info if someone else will encounter such an issue.

**Comment by maxisam** [comment]
That is definitely weird. I also use Cilium CNI with l2 announcement

**Comment by maxisam** [comment]
ummm, i still have the same issue over time. 

I got ipvs rules on all 3 nodes.

**Comment by thebsdbox** [comment]
@maxisam is this using kube-proxy replacement?

**Comment by maxisam** [comment]
> [@maxisam](https://github.com/maxisam) is this using kube-proxy replacement?
yeah, i use cilium with kubeProxyReplacement = true

**Comment by Cellebyte** [comment]
@maxisam could we close the issue and we would open one specifically for using kube-vip with cilium?

**Comment by Cellebyte** [comment]
Closed, @maxisam I still don't see an issue regarding you cilium challenges.

**Comment by todaygood** [comment]
which release version contained  this patch?
